name: admin-ui-paging
namespace: official
version: 1.1.0-4
author: Wazo Team
display_name: Paging
min_wazo_version: 18.02
tags:
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-paging
icon: bullhorn
