name: admin-ui-paging
namespace: official
version: 0.0.2
author: Wazo Team
display_name: Paging
min_wazo_version: 17.16
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-paging
